import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";
import { GoogleGenAI, Type } from "@google/genai";
import { createServer as createViteServer } from "vite";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "50mb" }));

function getGeminiClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is missing.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// Health check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// API: Generate 5-page outline and cover prompt
app.post("/api/generate-plan", async (req, res) => {
  try {
    const { childName, theme, ageGroup = "3-8 years" } = req.body;
    if (!theme || !childName) {
      return res.status(400).json({ error: "childName and theme are required." });
    }

    const ai = getGeminiClient();

    const prompt = `Create a 5-page children's coloring book plan for a child named "${childName}" with the theme "${theme}".
Target age group: ${ageGroup}.

Rules:
1. Provide a fun, catchy book title featuring the child's name (e.g., "${childName}'s Space Dinosaur Adventure").
2. Provide a playful book subtitle.
3. For each of the 5 pages, provide:
   - pageNumber (1 through 5)
   - title: Short, catchy title for the scene (3-6 words)
   - description: A delightful 1-sentence caption or mini-story that explains what is happening in the scene for the child to read or have read to them.
   - imagePrompt: A detailed, highly specific prompt designed specifically for an AI image generator to produce a black-and-white coloring page with thick bold outlines, no grayscale, no shading, pure white background, cute friendly characters, simple backgrounds suitable for coloring with crayons.
4. Also provide a coverImagePrompt for a cover illustration depicting ${childName}'s theme with bold lines, cute main character, welcoming pose.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction:
          "You are a master children's coloring book author and illustrator planner. You specialize in designing joyful, cohesive 5-page story arcs with clear, age-appropriate scenes and precise image prompts for clean, thick-line coloring pages.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            bookTitle: { type: Type.STRING },
            bookSubtitle: { type: Type.STRING },
            coverImagePrompt: { type: Type.STRING },
            pages: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  pageNumber: { type: Type.INTEGER },
                  title: { type: Type.STRING },
                  description: { type: Type.STRING },
                  imagePrompt: { type: Type.STRING },
                },
                required: ["pageNumber", "title", "description", "imagePrompt"],
              },
            },
          },
          required: ["bookTitle", "bookSubtitle", "coverImagePrompt", "pages"],
        },
      },
    });

    const parsed = JSON.parse(response.text || "{}");
    return res.json(parsed);
  } catch (error: any) {
    console.error("Error generating coloring book plan:", error);
    return res.status(500).json({
      error: error?.message || "Failed to generate coloring book outline.",
    });
  }
});

// Helper for generating an image with gemini-3-pro-image-preview
async function generateColoringImageWithModel(
  ai: GoogleGenAI,
  modelName: string,
  fullPrompt: string,
  imageSize: "1K" | "2K" | "4K"
) {
  const response = await ai.models.generateContent({
    model: modelName,
    contents: {
      parts: [
        {
          text: fullPrompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "3:4",
        imageSize: imageSize,
      },
    },
  });

  const candidates = response.candidates;
  if (!candidates || candidates.length === 0) {
    throw new Error("No image generated by the model.");
  }

  const parts = candidates[0].content?.parts || [];
  for (const part of parts) {
    if (part.inlineData && part.inlineData.data) {
      const mimeType = part.inlineData.mimeType || "image/png";
      return `data:${mimeType};base64,${part.inlineData.data}`;
    }
  }

  throw new Error("Image data was not returned by the model.");
}

// API: Generate single coloring page image
app.post("/api/generate-image", async (req, res) => {
  try {
    const { prompt, imageSize = "1K", isCover = false } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required." });
    }

    const validatedSize = ["1K", "2K", "4K"].includes(imageSize) ? imageSize : "1K";

    const ai = getGeminiClient();

    // Construct thick-line coloring book prompt
    const enhancedPrompt = `Children's coloring book page, black and white line art only, clean thick bold continuous black contours, crisp clean outlines, pure white background, zero color, zero shading, zero hatching, zero greyscale, zero gradients, wide open spaces to color inside the lines, friendly whimsical charming cartoon style for kids: ${prompt}`;

    // Target model: gemini-3-pro-image-preview as requested
    let imageUrl = "";
    try {
      imageUrl = await generateColoringImageWithModel(
        ai,
        "gemini-3-pro-image-preview",
        enhancedPrompt,
        validatedSize
      );
    } catch (primaryErr: any) {
      console.warn("gemini-3-pro-image-preview error, attempting fallback:", primaryErr?.message);
      try {
        imageUrl = await generateColoringImageWithModel(
          ai,
          "gemini-3-pro-image",
          enhancedPrompt,
          validatedSize
        );
      } catch (secondaryErr: any) {
        console.warn("gemini-3-pro-image fallback error, trying gemini-3.1-flash-image:", secondaryErr?.message);
        imageUrl = await generateColoringImageWithModel(
          ai,
          "gemini-3.1-flash-image",
          enhancedPrompt,
          validatedSize
        );
      }
    }

    return res.json({
      imageUrl,
      imageSize: validatedSize,
      isCover,
    });
  } catch (error: any) {
    console.error("Error in generate-image:", error);
    return res.status(500).json({
      error: error?.message || "Failed to generate coloring page image.",
    });
  }
});

// API: Multi-turn Chatbot (Coloring Guide & Story Assistant)
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, modelPreference = "gemini-3.5-flash", contextInfo } = req.body;

    if (!Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: "Messages array is required." });
    }

    const ai = getGeminiClient();

    // Model selection based on user instruction:
    // "Use gemini-3.1-pro-preview for particularly complex tasks, gemini-3.5-flash for general tasks, and gemini-3.1-flash-lite for tasks that should happen fast."
    let selectedModel = "gemini-3.5-flash";
    if (modelPreference === "gemini-3.1-pro-preview") {
      selectedModel = "gemini-3.1-pro-preview";
    } else if (modelPreference === "gemini-3.1-flash-lite") {
      selectedModel = "gemini-3.1-flash-lite";
    }

    const systemInstruction = `You are "Doodle", a warm, enthusiastic, and creative children's coloring book assistant and story guide.
Your role:
- Help children, parents, and teachers brainstorm enchanting coloring book themes (e.g., "Deep Sea Astronaut Animals", "Cozy Bakery Kittens", "Steampunk Safari").
- Suggest fun 5-page story ideas and page-by-page scenes.
- Provide creative color palette tips (e.g. "What colors make a space dinosaur pop? Try lime green with cosmic violet spots!").
- Suggest rhyming couplets or fun captions for coloring book pages.
- Give tips for coloring techniques suitable for young kids (wax crayons, colored pencils, washable markers).
- If the user asks for theme ideas, format them cleanly with bullet points and highlight catchy ideas they can copy-paste or click.
- Current active app context: ${contextInfo ? JSON.stringify(contextInfo) : "None yet"}.
Keep your tone encouraging, friendly, playful, and concise.`;

    // Format chat contents for Gemini
    // Map messages: role 'assistant' -> 'model', role 'user' -> 'user'
    const contents = messages.map((m: { role: string; text: string }) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.text }],
    }));

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    return res.json({
      reply: response.text || "I'd love to help you design a fun coloring book! What theme would you like to explore?",
      modelUsed: selectedModel,
    });
  } catch (error: any) {
    console.error("Error in chat endpoint:", error);
    return res.status(500).json({
      error: error?.message || "Failed to process chat message.",
    });
  }
});

// Vite Middleware or Static Production Serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // Express v4 wildcard route
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer();
